spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user?useSSL=false&useServerPreStmts=true&allowPublicKeyRetrieval=true
    username: root
    password: '!@#123ToBeHappy'
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
logging:
  level:
    root: warn
